#!/bin/sh

BASEDIR=$(dirname "$0")
SCRIPT_NAME=$(basename "$0")

PYTHON=/usr/bin/python3
SCRIPT=$BASEDIR/$SCRIPT_NAME

if [ -f "$SCRIPT.py" ]; then
	$PYTHON $SCRIPT.py "$@"
else
	$PYTHON $SCRIPT.pyc "$@"
fi
